AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Celosia: CFN Template to create a Lambda Function. 

Metadata:
  TemplateName: lambda-function-stack.yaml
  TemplateType: Lambda Function
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Celosia
  Modification History:
    - 1.0.0  - Oct 19, 2023   -- Initial Version
  Resources: 
    - Resources
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: "Project And Environment:"
      Parameters: 
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
      - StackName
    #################################### Code Repository Bucket ####################################
    - Label:
        default: "Code Repository S3 Bucket:"
      Parameters:
      - CodeRepositoryS3Bucket
      - KmsMasterKeyId
    #################################### Lambda Function ###########################################
    - Label:
        default: "Lambda Function Configuration:"
      Parameters: 
      - LambdaExecutionRoleArn
      - LambdaFunctionTimeoutSecs
      - LambdaRuntime
      - LambdaFunctionMemory
      - LambdaFunctionBaseName
      - LambdaFunctionDescription
      - LambdaReservedConcurrency
    #################################### DynamoDB Table ############################################
      - SNSTopicBaseName
    #################################### Step Function #############################################
    - Label:
        default: "Step Function Configuration:"
    ParameterLabels:
      #################################### Project Name and Environment ##############################
      ProjectName:
        default: "Project Name."
      Environment:
        default: "Environment Name."
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref."
      GitHubURL:
        default: "GitHub URL."
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA:
        default: "GitHub SHA"
      GitHubRepository:
        default: "GitHub Repository."
      CiBuild:
        default: "Ci Build."
      StackName:
        default: "Stack Name."
      ################################## Code Repository Bucket ####################################
      CodeRepositoryS3Bucket:
        default: "Code Repository S3 Bucket."
      KmsMasterKeyId:
        default: "KMS Master Key Id."
      ################################## Lambda Function ###########################################
      LambdaExecutionRoleArn: 
        default: "Lammba Function Execution Role Arn."
      LambdaFunctionTimeoutSecs:
        default: "Lambda Function Timeout in Seconds."
      LambdaRuntime: 
        default: "Lambda Runtime."
      LambdaFunctionMemory:
        default: "Lambda Fuction Memory."
      LambdaFunctionBaseName:
        default: "Name of the Lambda Function."
      LambdaFunctionDescription:
        default: "Lambda Function Description."
      LambdaReservedConcurrency:
        default: "Lambda Reserved Concurrency."
      ################################## DynamoDB Table ############################################
      SNSTopicBaseName: 
        default: "DynamoDB Table Name."
Parameters:
  ########################################### Project Name and Environment #######################
  ProjectName:
    Default: project
    Description: "The Project Name."
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### Code Repository Bucket ####################################
  CodeRepositoryS3Bucket:
    Default: subhamay-projects-repository-us-east-1
    Description: "S3 Bucket Storing The Lambda Code."
    Type: String
    MinLength: 10
    MaxLength: 63
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 63, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ###################################### KMS Key ###################################################
  KmsMasterKeyId:
    Default: "arn:aws:kms:us-east-1:237376087602:key/f7eb118d-f1d2-4d70-a046-dfada470840e"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 75
    MaxLength: 75
    AllowedPattern: "[a-z:/0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."    
  ###################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  StackName:
    Default: ""
    Description: "The name of the stack which created the resource"
    Type: String  
  ######################################## Lambda Function ########################################
  LambdaExecutionRoleArn:
    Default: arn:aws:iam::111111111111:role/lambda-role
    Description: Lambda Execution Role Arn
    Type: String
    MinLength: 40
    MaxLength: 100
    AllowedPattern: "[a-zA-Z0-9-:/]*"
    ConstraintDescription: The length should be between 40 and 100, must contain only letters and should start with an uppercase letter.
  LambdaRuntime:
    Default: python3.8
    Description: "Lambda Runtime (Python 3.7, 3.8 or 3.9)"
    Type: String
    AllowedValues: [python3.7 ,python3.8, python3.9]
    ConstraintDescription: "The Lambda runtime should be either Python 3.7, 3.8 or 3.9"
  LambdaFunctionTimeoutSecs:
    Default: 300
    Description: Lambda function timeout period in seconds.
    Type: Number
    MinValue: 3
    MaxValue: 900
    ConstraintDescription: The Lambda timeout period should be between 3 and 900 seconds.
  LambdaFunctionMemory:
    Default: 256
    Description: The Lambda Function Memory in MB.
    Type: Number
    MinValue: 128
    MaxValue: 10240
    ConstraintDescription: The Lambda Memory should be between 128 and 10240.
  LambdaFunctionBaseName:
    Default: insert-data
    Description: Lambda Function Name
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-]*"
    ConstraintDescription: The length should be between 15 and 50, must contain only lowercase letters,numbers and dash(-) and should start with a letter.
  LambdaFunctionDescription:
    Default: The Processing Lambda Function.
    Description: The Lambda Function Description
    Type: String
    MinLength: 30
    MaxLength: 200
    AllowedPattern: "^[A-Z][a-zA-Z0-9 .,]*$"
    ConstraintDescription: The length should be between 30 and 300, must contain only lowercase letters,space( ) and dot(.) and should start with an uppercase letter.
  LambdaReservedConcurrency:
    Default: 1
    Description: "Lambda Reserved Concurrency"
    Type: Number
    MinValue: 0
    MaxValue: 5  
  ###################################### DynamoDB Table ############################################
  SNSTopicBaseName:
    Default: sns-topic
    Description: "The Name Of The SNS Topic."
    Type: String
    MinLength: 6
    MaxLength: 40
    AllowedPattern: "[a-z][a-z0-9-]*"
    ConstraintDescription: "The length should be between 10 and 40, must contain only lowercase letter, number, dash and should start with a letter."
Resources:
  ###################################### Lambda Function Log Group #################################
  LambdaFunctionLogGroup:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Type: AWS::Logs::LogGroup
    Properties: 
      KmsKeyId: !Ref KmsMasterKeyId
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${LambdaFunctionBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      RetentionInDays: 14
      Tags: 
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: CodeRepositoryS3Bucket
          Value: !Ref CodeRepositoryS3Bucket
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
        - Key: StackName
          Value: !Ref StackName
  ######################################## Lambda Function ########################################
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: !Ref LambdaRuntime
      FunctionName: !Sub  '${ProjectName}-${LambdaFunctionBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      Description: !Ref LambdaFunctionDescription
      Role: !Ref LambdaExecutionRoleArn
      Handler: !Sub '${LambdaFunctionBaseName}.lambda_handler'
      Code:
        S3Bucket: !Ref CodeRepositoryS3Bucket
        S3Key: !Sub '${GitHubRepository}/code/${LambdaFunctionBaseName}.zip'
      Timeout: !Ref LambdaFunctionTimeoutSecs
      MemorySize: !Ref LambdaFunctionMemory
      TracingConfig:
        Mode: Active
      ReservedConcurrentExecutions: !Ref LambdaReservedConcurrency
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${SNSTopicBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key:  Environment
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
      - Key: StackName
        Value: !Ref StackName
Outputs:
  LambdaFunctionLogGroupArn:
    Description: The Arn of the Lambda Function Log Group
    Value: !GetAtt LambdaFunctionLogGroup.Arn
  LambdaFunctionArn: 
    Description: The Arn of the Lambda Function
    Value: !GetAtt LambdaFunction.Arn
